# Generated by Django 4.1.2 on 2022-10-16 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictModelProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name=uuid.uuid4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN PROCESS", "In Process"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="IN PROCESS",
                        max_length=50,
                    ),
                ),
                ("response", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
