# Generated by Django 4.1.2 on 2022-10-16 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0002_predictmodelprocess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictmodelprocess",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
